env:
  global:
    - MAKEFLAGS="-j 2"
    - GO111MODULE="on"
    - NODE_ENV="test"

language: go
go:
  - 1.12.x

before_install:
  - nvm install v11.15

install:
  - make build

script:
  - make test

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/.cache/yarn
    - $GOPATH/pkg/mod
