env:
  global:
    - MAKEFLAGS="-j 2"

language: go
go:
  - 1.11.x
  - 1.12.x

before_install:
  - nvm install latest

install:
  - make

script:
  - make test

cache:
  directories:
    - "node_modules"
