env:
  global:
    - MAKEFLAGS="-j 2"
    - GO111MODULE="on"
    - TAIPAN_ENV="test"
    - NODE_ENV="test"

language: go
go:
  - 1.12.x

addons:
  mariadb: '10.3'

before_install:
  - nvm install v11.15
  - ./scripts/gen-test-config
  - mysql -e 'CREATE DATABASE `taipan_test` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;'
  - mysql taipan_test < web/sql/schema.sql

install:
  - make build

script:
  - make test

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/.cache/yarn
    - $GOPATH/pkg/mod
