env:
  global:
    - MAKEFLAGS="-j 2"
    - GO111MODULE="on"

language: go
go:
  - 1.11.x
  - 1.12.x

before_install:
  - nvm install v11.15

install:
  - make

script:
  - make test

cache:
  directories:
    - "node_modules"
