env:
  global:
    - MAKEFLAGS="-j 2"
    - GO111MODULE="on"
    - TAIPAN_ENV="test"
    - NODE_ENV="test"

language: go
go:
  - 1.12.x

# addons:
#   mariadb: '10.3'

before_install:
  - nvm install v11.15
  # - ./scripts/create-test-config
  # - ./scripts/create-test-database

install:
  - make build

script:
  - make test

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/.cache/yarn
    - $GOPATH/pkg/mod
