env:
  global:
    - MAKEFLAGS="-j 2"
    - GO111MODULE="on"
    - TAIPAN_ENV="test"
    - NODE_ENV="test"

language: go
go:
  - 1.12.x

# addons:
#   mariadb: '10.3'
#   apt:
#     packages:
#       - libgconf-2-4

before_install:
  - nvm install v11.15
  # - go get honnef.co/go/tools/cmd/staticcheck
  # - ./scripts/create-test-config
  # - ./scripts/create-test-database

install:
  - make build

# before_script:
#   - make run &

script:
  - make analyse
  - make test
  # - make test-e2e

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/.cache/yarn
    - $GOPATH/pkg/mod
