name: Taipan - Master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
    - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - uses: actions/cache@v1
        with:
          path: web/app/node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('web/app/yarn.lock') }}
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod') }}
      - run: make build
      - run: make analyse
      - run: make test
        env:
          NODE_ENV: test
          TAIPAN_ENV: test
